import Head from "next/head";
import Image from "next/image";
import Layout from "../src/components/layout"; 
import Cta from "../src/components/cta";
import AboutExcerpt from "../src/components/aboutExcerpt";
import Banner from "../src/components/header/banner";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Banner />
      <AboutExcerpt />
      <Cta /> 
    </Layout>
  );
}
